name: Type check

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  test:
    timeout-minutes: 20
    name: unit test
    runs-on: ubuntu-latest

    steps:
      - name: setup repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: cache node_modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - name: install node_modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run type check
        run: npm run check:tsc
      - run: echo "🍏 This job's status is ${{ job.status }}."
